services:
  web:
    image: case4classification:1.0
    environment:
      - gpus=all
    network_mode: "host"
    container_name: case4classification_light
    volumes:
      - /mnt/data/roberta3_large_ext:/workspace/roberta3_large_ext
      - /mnt/data/ayfl-4/model/rbt3l:/workspace/model/rbt3l/
      - /mnt/data/ayfl-4/log:/workspace/data
    command: python3 torch_server.py -c config/roberta3_large_bert_config.json -p 58084
